name: Publish Resume
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile LaTeX doc
        uses: dante-ev/latex-action@latest
        with:
          root_file: resume.tex
          compiler: pdflatex
      - name: Publish
        uses: SierraSoftworks/gh-releases@v1.0.7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            out/resume.pdf