name: Publish Resume
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Compile LaTeX doc
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: resume.tex
          compiler: pdflatex
      - name: Set current date as env var
        run: echo NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Publish
        uses: xresloader/upload-to-github-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: "resume.pdf"
          branches: "main"
          default_release_name: ${{ env.NOW }}
